#!/usr/bin/env bash
# Install a generated CPC Isabelle session into this tree.

set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/install.sh

Run tools/eoc/cpc/install_iogos from an Ethos checkout against this
repository. That compiles the whole CPC signature through the Eunoia
compiler's isabelle-meta backend and copies the session it publishes into
Cpc/, adding a Cpc line to ROOTS the first time.

The wrapper only points the installer at this tree; every EOC_* setting the
installer documents still applies, and this passes them through untouched.

  ETHOS_DIR       the Ethos checkout (default ~/ethos)
  BUILD_DIR       where ethos-eoc is built (default $ETHOS_DIR/build-eoc)
  EOC_NO_BUILD=1  do not rebuild ethos-eoc first
  EOC_CPC_INPUT   the CPC signature to compile
  EOC_SEMANTICS   what that signature's symbols mean to the model

Examples:
  scripts/install.sh
  EOC_NO_BUILD=1 scripts/install.sh
  ETHOS_DIR=/path/to/ethos scripts/install.sh
USAGE
}

case "${1:-}" in
  -h|--help) usage; exit 0 ;;
esac

if [[ $# -gt 0 ]]; then
  echo "error: scripts/install.sh takes no arguments; configure it through the" >&2
  echo "       environment. Run scripts/install.sh --help for the list." >&2
  exit 2
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

ETHOS_DIR="${ETHOS_DIR:-$HOME/ethos}"
installer="${ETHOS_DIR}/tools/eoc/cpc/install_iogos"

if [[ ! -x "${installer}" ]]; then
  cat >&2 <<MSG
error: no installer at ${installer}.

The calculus is generated by the Eunoia compiler in an Ethos checkout, which
this repository does not vendor. Clone https://github.com/cvc5/ethos and set
ETHOS_DIR to it, or put the checkout at ~/ethos.
MSG
  exit 1
fi

# Not passed on the command line: the installer reads its destination, and
# everything else, from the environment. Its own defaults stand for the rest.
exec env IOGOS_DIR="${repo_root}" "${installer}"
